clc;
clear all;
fm=5e3;
fc=100e3;
ka=0.25;
Ac=1;
Am=input('Enter peak amplitude of message signal');
mu=ka*Am;
fs=16*fc;
t=0:(1/fs):(100e-3);
m=Am*cos(2*pi*fm*t);
c=Ac*cos(2*pi*fc*t);
s=(1+ka*m).*c;
ax=t(1:1000);
figure;
subplot(4,1,1);
plot(ax,m(1:1000));
xlabel('Time(s)');
ylabel('Amplitude');
title('MESSAGE SIGNAL');
subplot(4,1,2);
plot(ax,c(1:1000));
xlabel('Time(s)');
ylabel('Amplitude');
title('CARRIER SIGNAL');
subplot(4,1,3);
plot(ax,s(1:1000));
xlabel('Time(s)');
ylabel('Amplitude');
title('MODULATED SIGNAL');
subplot(4,1,4);
[yupper,ylower]=envelope(s);
plot(ax,yupper(1:1000));
xlabel('Time(s)');
ylabel('Amplitude');
title('DEMODULATED SIGNAL');
[ps,f]=pspectrum(s,fs,'FrequencyResolution',500);
figure;
plot(f,10*log10(ps));
axis([0 200*10^3 -70 10]);
title('FREQUENCY SPECTRUM OF MODULATED SIGNAL');
xlabel('Frequency(Hz)');
ylabel('Power(dB)');
