clc;
clear all;
Am = input('Enter the amplitude of the message signal:');
kf = 10e3;
fm = 5e3;
delf= kf*Am;
beta = delf/fm;
fc = 200e3;
Ac = sqrt(2);
fs = 16*fc;
t = 0:1/fs:1000e-3;
m = Am*cos(2*pi*fm*t);
c = Ac*cos(2*pi*fc*t);
s = Ac*cos(2*pi*fc*t + beta*sin(2*pi*fm*t));
y = s;
[ps,f]=pspectrum(y,fs,'FrequencyResolution',100);
figure;
plot(f/1e3,10*log10(ps));
xlabel('Frequency (kHz)'); ylabel('Power(dB)');
axis([10 400 -70 10]);
title('FREQUENCY SPECTRUM');
mout = fmdemod(y,fc,fs,kf*Am);
figure;
subplot(5,1,1);
plot(t(1:1000),m(1:1000));
title('MODULATING SIGNAL');
xlabel('Time(s)'); ylabel('Amplitude');
subplot(5,1,2);
plot(t(1:1000),c(1:1000));
title('CARRIER SIGNAL');
xlabel('Time(s)'); ylabel('Amplitude');
subplot(5,1,3);
plot(t(1:1000),s(1:1000));
title('MODULATED SIGNAL');
xlabel('Time(s)'); ylabel('Amplitude');
subplot(5,1,4);
plot(t(1:1000),y(1:1000));
title('RECEIVED SIGNAL');
xlabel('Time(s)');
ylabel('Amplitude');
subplot(5,1,5);
plot(t(1:1000),mout(1:1000));
title('DEMODULATED SIGNAL');
xlabel('Time(s)'); ylabel('Amplitdue');